/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frame;

import java.awt.BorderLayout;
import java.net.URL;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import tubes.Koneksi;
import tubes.WrapLayout;

/**
 *
 * @author daapinn
 */
public class cart extends javax.swing.JFrame {
    
    

private javax.swing.JPanel itemsPanel;
private javax.swing.JScrollPane jScrollPane1;
    private int userID;
  
   public cart(int userID) {
    initComponents();
    this.userID = userID;
    jPanel2.setLayout(new WrapLayout(WrapLayout.LEFT,10,10));

}
 void deleteAllCartItems() {
    try {
        Connection connection = Koneksi.getKoneksi();
        String sql = "DELETE FROM cart_items WHERE id = ?";
        PreparedStatement statement = connection.prepareStatement(sql);
        statement.setInt(1, userID);
        int rowsAffected = statement.executeUpdate();

        if (rowsAffected > 0) {
            JOptionPane.showMessageDialog(this, "Cart items deleted successfully!");
            displayCartItems();
        } else {
            JOptionPane.showMessageDialog(this, "Failed to delete cart items.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    } catch (SQLException e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Error deleting cart items.", "Error", JOptionPane.ERROR_MESSAGE);
    }
}
void displayCartItems() {
    try {
        Connection connection = Koneksi.getKoneksi();
        String sql = "SELECT * FROM cart_items WHERE id = ?";
        PreparedStatement statement = connection.prepareStatement(sql);
        statement.setInt(1, userID);
        ResultSet resultSet = statement.executeQuery();

        // Clear the panel before adding new items
        jPanel2.removeAll();
        jPanel2.revalidate();
        jPanel2.repaint();

        // Loop through the items and add them to the panel
        while (resultSet.next()) {
            String CartID = resultSet.getString("cart_id");
            String imagePath = resultSet.getString("image_path");

            ImageIcon icon = null;
            try {
                URL imageUrl = getClass().getResource(imagePath);
                if (imageUrl != null) {
                    icon = new ImageIcon(imageUrl);
                }
            } catch (Exception e) {
                e.printStackTrace();
            }

            card a = new card();
            // Assuming you have a label in the card class to display the image
            a.getLabel1().setIcon(icon);

            jPanel2.add(a);
        }

        // If there are no items in the cart, display a message or handle it accordingly
        if (jPanel2.getComponentCount() == 0) {
            card emptyCard = new card();
            emptyCard.getLabel1().setText("Your cart is empty.");
            jPanel2.add(emptyCard);
        }

        jPanel2.revalidate();
        jPanel2.repaint();
    } catch (SQLException e) {
        e.printStackTrace();
        System.out.println("Error retrieving cart items.");
    }
}



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        DeleteBtn = new javax.swing.JLabel();
        BtnBuy = new javax.swing.JLabel();
        abo = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/Shopping Cart.png"))); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/Journey!.png"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, -1, -1));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        jScrollPane2.setViewportView(jPanel2);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 1000, 450));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/CONTACT.png"))); // NOI18N
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 50, -1, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/ORDER DETAIL.png"))); // NOI18N
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 230, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/ORDER DETAIL.png"))); // NOI18N
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 230, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/HOME.png"))); // NOI18N
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 50, -1, -1));

        DeleteBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/Group 80.png"))); // NOI18N
        DeleteBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        DeleteBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DeleteBtnMouseClicked(evt);
            }
        });
        jPanel1.add(DeleteBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 700, 170, -1));

        BtnBuy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/Group 79.png"))); // NOI18N
        BtnBuy.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnBuy.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnBuyMouseClicked(evt);
            }
        });
        jPanel1.add(BtnBuy, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 700, 170, -1));

        abo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/ABOUT.png"))); // NOI18N
        abo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        abo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                aboMouseClicked(evt);
            }
        });
        jPanel1.add(abo, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 50, -1, 20));

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/Rectangle 21.png"))); // NOI18N
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/Rectangle 4.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1080, 110));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1080, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 760, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void aboMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aboMouseClicked
        // TODO add your handling code here:
        this.dispose();
        about ab = new about(userID);
        ab.setVisible(true);
    }//GEN-LAST:event_aboMouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        // TODO add your handling code here:
        this.dispose();
        homepage hp=new homepage(userID);
        hp.setVisible(true);
    }//GEN-LAST:event_jLabel5MouseClicked

    private void DeleteBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DeleteBtnMouseClicked
        // TODO add your handling code here:
        int confirmDialog = JOptionPane.showConfirmDialog(this, "Are you sure you want to delete all items from your cart?", "Confirm Delete", JOptionPane.YES_NO_OPTION);
    if (confirmDialog == JOptionPane.YES_OPTION) {
        deleteAllCartItems();
    }

    }//GEN-LAST:event_DeleteBtnMouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        this.dispose();
        contact ct=new contact(userID);
        ct.setVisible(true);
    
    }//GEN-LAST:event_jLabel2MouseClicked

    private void BtnBuyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnBuyMouseClicked
    
        try {
        Connection connection = Koneksi.getKoneksi();
        String sql = "SELECT SUM(price) AS total FROM cart_items WHERE id = ?";
        PreparedStatement statement = connection.prepareStatement(sql);
        statement.setInt(1, userID);
        ResultSet resultSet = statement.executeQuery();

        double total = 0.0;

        // Calculate the total price of items in the cart
        if (resultSet.next()) {
            total = resultSet.getDouble("total");
        }

        // ... Your code for moving data to the new database (if needed)

        // Display a confirmation dialog to inform the user about the successful purchase
        int confirmDialog = JOptionPane.showConfirmDialog(this, "Your purchase was successful!\nTotal amount: " + total + "\nDo you want to proceed to payment confirmation?", "Purchase Complete", JOptionPane.YES_NO_OPTION);

        if (confirmDialog == JOptionPane.YES_OPTION) {
            // Create an instance of the confirm class and open it
            this.dispose(); // Close the cart window
            cart cartInstance = new cart(userID);
    confirm confirmFrame = new confirm(total, userID, cartInstance);
    confirmFrame.setVisible(true);
        } else if(confirmDialog == JOptionPane.NO_OPTION) {
        } 
    } catch (SQLException e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Error during purchase. Please try again.", "Error", JOptionPane.ERROR_MESSAGE);
    }
        }//GEN-LAST:event_BtnBuyMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

      
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BtnBuy;
    private javax.swing.JLabel DeleteBtn;
    private javax.swing.JLabel abo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
