/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frame;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import tubes.Koneksi;

/**
 *
 * @author Andrian Baros
 */
public class confirm extends javax.swing.JFrame {
    private double subtotal;
    private cart cartInstance;

    
    private int userID;

    public confirm(double subtotal, int userID, cart cartInstance) {
        initComponents();
        this.subtotal = subtotal;
        this.userID = userID;
        this.cartInstance = cartInstance; // Initialize the cart instance

        SubtotalTXT.setText(Double.toString(subtotal));
    }
private String getLastPaymentID() {
        String lastPaymentID = null;
        try {
            Connection connection = Koneksi.getKoneksi();
            String sql = "SELECT paymentid FROM payment_table ORDER BY paymentid DESC LIMIT 1";
            PreparedStatement statement = connection.prepareStatement(sql);
            ResultSet resultSet = statement.executeQuery();

            if (resultSet.next()) {
                lastPaymentID = resultSet.getString("paymentid");
            }
            resultSet.close();
            statement.close();
        } catch (SQLException e) {
            e.printStackTrace();
        }
        return lastPaymentID;
    }
      private String generatePaymentID() {
        // In this method, you can use a combination of a static prefix and an auto-incremented value.
        // For example, you can use the "JRN" prefix and auto-increment the payment ID.
        // You need to fetch the latest payment ID from the database and then increment it to generate the new one.

        // Assuming you have a method to fetch the last payment ID from the database, let's call it "getLastPaymentID()"
        String lastPaymentID = getLastPaymentID(); // Implement this method to fetch the last payment ID from the database

        // Parse the numeric part of the last payment ID and increment it by 1
        int numericPart = 1; // Default value if no last payment ID is found
        if (lastPaymentID != null && !lastPaymentID.isEmpty()) {
            numericPart = Integer.parseInt(lastPaymentID.substring(3)); // Assuming the numeric part starts from the 4th character
            numericPart++; // Increment the numeric part
        }

        // Combine the prefix and the new numeric part to form the new payment ID
        String newPaymentID = "JRN" + String.format("%03d", numericPart);

        return newPaymentID;
    
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel10 = new javax.swing.JLabel();
        bca = new javax.swing.JRadioButton();
        qris = new javax.swing.JRadioButton();
        dana = new javax.swing.JRadioButton();
        SubtotalTXT = new javax.swing.JTextField();
        NameTXT = new javax.swing.JTextField();
        PhoneTXT = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        Address = new javax.swing.JTextArea();
        BtnPay = new javax.swing.JLabel();
        BtnReset = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/dana.png"))); // NOI18N
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 390, -1, -1));

        bca.setBackground(new java.awt.Color(31, 31, 31));
        buttonGroup1.add(bca);
        getContentPane().add(bca, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 420, -1, -1));

        qris.setBackground(new java.awt.Color(31, 31, 31));
        buttonGroup1.add(qris);
        getContentPane().add(qris, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 420, -1, -1));

        dana.setBackground(new java.awt.Color(31, 31, 31));
        buttonGroup1.add(dana);
        getContentPane().add(dana, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 420, -1, -1));

        SubtotalTXT.setFont(new java.awt.Font("Ebrima", 1, 13)); // NOI18N
        SubtotalTXT.setForeground(new java.awt.Color(255, 255, 255));
        SubtotalTXT.setOpaque(false);
        getContentPane().add(SubtotalTXT, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 330, 350, 30));

        NameTXT.setFont(new java.awt.Font("Ebrima", 1, 13)); // NOI18N
        NameTXT.setForeground(new java.awt.Color(255, 255, 255));
        NameTXT.setOpaque(false);
        getContentPane().add(NameTXT, new org.netbeans.lib.awtextra.AbsoluteConstraints(179, 260, 350, 30));

        PhoneTXT.setFont(new java.awt.Font("Ebrima", 1, 13)); // NOI18N
        PhoneTXT.setForeground(new java.awt.Color(255, 255, 255));
        PhoneTXT.setOpaque(false);
        getContentPane().add(PhoneTXT, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 260, 350, 30));

        Address.setColumns(20);
        Address.setFont(new java.awt.Font("Ebrima", 1, 13)); // NOI18N
        Address.setRows(5);
        Address.setOpaque(false);
        jScrollPane1.setViewportView(Address);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 366, 470, 100));

        BtnPay.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/Group 81.png"))); // NOI18N
        BtnPay.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnPayMouseClicked(evt);
            }
        });
        getContentPane().add(BtnPay, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 620, -1, -1));

        BtnReset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/reset.png"))); // NOI18N
        BtnReset.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnResetMouseClicked(evt);
            }
        });
        getContentPane().add(BtnReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 620, -1, -1));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/HOME.png"))); // NOI18N
        jLabel14.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel14MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 50, -1, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/Payment.png"))); // NOI18N
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 390, -1, -1));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/bca.png"))); // NOI18N
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 390, -1, -1));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/qris.png"))); // NOI18N
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 390, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/address.png"))); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 320, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/subtotal.png"))); // NOI18N
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 320, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/paymentconfirmtext.png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/phone.png"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 250, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/name.png"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/attention.png"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/Journey!.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/Rectangle 23.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/Rectangle 50.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BtnPayMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnPayMouseClicked
        if (NameTXT.getText().isEmpty() || Address.getText().isEmpty() || PhoneTXT.getText().isEmpty() || SubtotalTXT.getText().isEmpty()) {
        JOptionPane.showMessageDialog(this, "Please fill in all required fields.", "Validation Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    // Check which radio button is selected and show corresponding message
    if (qris.isSelected()) {
        JOptionPane.showMessageDialog(this, "Payment with QRIS successful!", "Payment Complete", JOptionPane.INFORMATION_MESSAGE);
    } else if (bca.isSelected()) {
        JOptionPane.showMessageDialog(this, "Payment with BCA successful!", "Payment Complete", JOptionPane.INFORMATION_MESSAGE);
    } else if (dana.isSelected()) {
        JOptionPane.showMessageDialog(this, "Payment with DANA successful!", "Payment Complete", JOptionPane.INFORMATION_MESSAGE);
    } else {
        JOptionPane.showMessageDialog(this, "Please select a payment method.", "Payment Method", JOptionPane.WARNING_MESSAGE);
        return;
    }
     String paymentID = generatePaymentID();

        try {
            Connection connection = Koneksi.getKoneksi();
            String sql = "INSERT INTO payment_table (paymentid, id, name, phone, address, subtotal) VALUES (?, ?, ?, ?, ?, ?)";
            PreparedStatement statement = connection.prepareStatement(sql);
            statement.setString(1, paymentID);
            statement.setInt(2, userID);
            statement.setString(3, NameTXT.getText());
            statement.setString(4, PhoneTXT.getText());
            statement.setString(5, Address.getText());
            statement.setDouble(6, Double.parseDouble(SubtotalTXT.getText()));

            int rowsAffected = statement.executeUpdate();

            if (rowsAffected > 0) {
            JOptionPane.showMessageDialog(this, "Payment successful! PaymentID: " + paymentID, "Payment Complete", JOptionPane.INFORMATION_MESSAGE);
            this.dispose();
            thanks tx = new thanks();
            tx.setVisible(true);
            // Clear the cart after successful payment
            if (cartInstance != null) {
                cartInstance.deleteAllCartItems();
            } else {
                System.out.println("Cart instance is not initialized."); // Handle this case accordingly
            }
        } else {
            JOptionPane.showMessageDialog(this, "Failed to complete payment.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    } catch (SQLException e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Error saving payment details.", "Error", JOptionPane.ERROR_MESSAGE);
    }


    }//GEN-LAST:event_BtnPayMouseClicked

    private void jLabel14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseClicked
        // TODO add your handling code here:
        this.dispose();
        homepage hp=new homepage(userID);
        hp.setVisible(true);
    }//GEN-LAST:event_jLabel14MouseClicked

    private void BtnResetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnResetMouseClicked
        // TODO add your handling code here:
        // Clear input fields
    NameTXT.setText("");
    Address.setText("");
    PhoneTXT.setText("");
    NameTXT.requestFocus();

    // Deselect radio buttons
    buttonGroup1.clearSelection();
    }//GEN-LAST:event_BtnResetMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(confirm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(confirm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(confirm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(confirm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea Address;
    private javax.swing.JLabel BtnPay;
    private javax.swing.JLabel BtnReset;
    private javax.swing.JTextField NameTXT;
    private javax.swing.JTextField PhoneTXT;
    private javax.swing.JTextField SubtotalTXT;
    private javax.swing.JRadioButton bca;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton dana;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton qris;
    // End of variables declaration//GEN-END:variables
}
