/* dapin
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frame;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.ImageIcon;
import javax.swing.Timer;

/**
 *
 */
public class homepage extends javax.swing.JFrame {
    private int userID;
    private Timer timer;
    private final String[] slideshowImages = {
        "/asset/gambar1.png",
        "/asset/gambar2.png",
        "/asset/gambar3.png",
        "/asset/gambar4.png",
        // Add more image paths as needed
    };
    private int currentSlide = 0;
    
    
    /**
     * Creates new form homepage
     */
    public homepage(int userID) {
        initComponents();
        this.userID = userID;
        // Create a Timer to change slides at regular intervals (e.g., 3 seconds)
        int delay = 2000; // 3 seconds
        ActionListener timerListener = new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                showNextSlide();
            }
        };
        timer = new Timer(delay, timerListener);
        timer.start();
    
    }
    

    
    // Method to display the current slide
    private void showSlide(int index) {
        String imagePath = slideshowImages[index];
        ImageIcon imageIcon = new ImageIcon(getClass().getResource(imagePath));
        slideshow1.setIcon(imageIcon);
    }
    
    // Method to show the next slide in the slideshow
    private void showNextSlide() {
        currentSlide = (currentSlide + 1) % slideshowImages.length;
        showSlide(currentSlide);
    }
    
    private void showPreviousSlide() {
    // Calculate the index of the previous slide
    currentSlide = (currentSlide - 1 + slideshowImages.length) % slideshowImages.length;
    showSlide(currentSlide);
}

  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel10 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        prevbtn = new javax.swing.JLabel();
        nextbtn = new javax.swing.JLabel();
        slideshow1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/SHOP.png"))); // NOI18N
        jLabel10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 50, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/Journey!.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/icon _cart_.png"))); // NOI18N
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 40, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/Component 1.png"))); // NOI18N
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 40, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/Rectangle 4.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 110));

        prevbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/Vector 3.png"))); // NOI18N
        prevbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        prevbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                prevbtnMouseClicked(evt);
            }
        });
        getContentPane().add(prevbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, -1, -1));

        nextbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/Vector 2.png"))); // NOI18N
        nextbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        nextbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nextbtnMouseClicked(evt);
            }
        });
        getContentPane().add(nextbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 400, -1, -1));

        slideshow1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/gambar1.png"))); // NOI18N
        getContentPane().add(slideshow1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 1080, 650));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        // TODO add your handling code here:
        this.dispose();
        profile profileForm = new profile(userID);
        profileForm.setVisible(true);
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        // TODO add your handling code here:
        this.dispose();
        cart sh=new cart(userID);
        sh.setVisible(true);
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        // TODO add your handling code here:
        this.dispose();
        shopping sc=new shopping(userID);
        sc.setVisible(true);
    }//GEN-LAST:event_jLabel10MouseClicked

    private void nextbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nextbtnMouseClicked
        // TODO add your handling code here:
        showNextSlide();
    }//GEN-LAST:event_nextbtnMouseClicked

    private void prevbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_prevbtnMouseClicked
        // TODO add your handling code here:
        showPreviousSlide();
    }//GEN-LAST:event_prevbtnMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
 
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel nextbtn;
    private javax.swing.JLabel prevbtn;
    private javax.swing.JLabel slideshow1;
    // End of variables declaration//GEN-END:variables
}
